// Drum one-shots: 111 of the 200 starter assets.
//
// Counts follow the docs/sample-library.md section 6.2 allocation scaled to the
// starter set, and each role covers the "required range" column for that row —
// clean through distorted, short through long, synthetic through acoustic-
// derived — rather than 20 near-identical variations of one voice.

/** @type {import("./index.mjs").CatalogEntry[]} */
export const KICKS = [
	{
		name: "Rounded Club Kick",
		params: { startHz: 130, endHz: 48, decay: 0.45 },
		genres: ["house", "electronic-pop", "uk-garage"],
		characters: ["round", "clean", "punchy"],
		intensity: "medium",
	},
	{
		name: "Tight House Kick",
		params: { startHz: 140, endHz: 55, decay: 0.3, clickAmount: 0.5 },
		genres: ["house", "uk-garage"],
		characters: ["tight", "punchy", "dry"],
		intensity: "medium",
	},
	{
		name: "Deep Sub Kick",
		params: {
			startHz: 110,
			endHz: 38,
			decay: 0.8,
			curve: 0.8,
			clickAmount: 0.15,
		},
		genres: ["dubstep", "techno", "trap"],
		characters: ["sub-heavy", "deep", "round"],
		intensity: "medium",
	},
	{
		name: "Soft Rounded Kick",
		params: {
			startHz: 120,
			endHz: 50,
			decay: 0.5,
			curve: 1.4,
			clickAmount: 0.08,
		},
		genres: ["lofi", "ambient", "hip-hop"],
		characters: ["soft", "round", "warm"],
		intensity: "low",
	},
	{
		name: "Driven Techno Kick",
		params: { startHz: 150, endHz: 50, decay: 0.5, drive: 4, noiseTail: 0.2 },
		genres: ["techno"],
		characters: ["distorted", "punchy", "dark"],
		intensity: "high",
	},
	{
		name: "Industrial Hammer Kick",
		params: {
			startHz: 190,
			endHz: 52,
			decay: 0.35,
			drive: 9,
			clickAmount: 0.6,
		},
		genres: ["techno", "dubstep"],
		characters: ["distorted", "abrasive", "metallic"],
		intensity: "extreme",
	},
	{
		name: "Short Punch Kick",
		params: { startHz: 135, endHz: 58, decay: 0.18, clickAmount: 0.55 },
		genres: ["techno", "breakbeat", "drum-and-bass", "jungle"],
		characters: ["short", "tight", "dry"],
		intensity: "medium",
	},
	{
		name: "Long Rumble Kick",
		params: {
			startHz: 120,
			endHz: 42,
			decay: 1.1,
			noiseTail: 0.35,
			drive: 1.6,
		},
		genres: ["techno", "dubstep"],
		characters: ["long", "deep", "layered"],
		intensity: "high",
	},
	{
		name: "Clicky Top Kick",
		params: {
			startHz: 160,
			endHz: 55,
			decay: 0.3,
			clickAmount: 0.95,
			clickCutoff: 4200,
		},
		genres: ["techno", "trance", "electronic-pop"],
		characters: ["bright", "tight", "punchy"],
		intensity: "medium",
	},
	{
		name: "Analog Triangle Kick",
		params: { startHz: 125, endHz: 47, decay: 0.42, bodyWaveform: "triangle" },
		genres: ["house", "techno", "lofi"],
		characters: ["warm", "round", "dry"],
		intensity: "medium",
	},
	{
		name: "Dusty Tape Kick",
		params: {
			startHz: 115,
			endHz: 52,
			decay: 0.28,
			drive: 2.6,
			clickCutoff: 1100,
		},
		genres: ["lofi", "hip-hop"],
		characters: ["warm", "gritty", "soft"],
		intensity: "low",
	},
	{
		name: "Trap Boom Kick",
		params: {
			startHz: 120,
			endHz: 42,
			decay: 0.9,
			pitchTau: 0.06,
			clickAmount: 0.3,
		},
		genres: ["trap", "hip-hop"],
		characters: ["deep", "sub-heavy", "long"],
		intensity: "medium",
	},
	{
		name: "Snapping Break Kick",
		params: {
			startHz: 210,
			endHz: 60,
			decay: 0.22,
			clickAmount: 0.85,
			drive: 1.8,
		},
		genres: ["drum-and-bass", "jungle", "breakbeat"],
		characters: ["tight", "bright", "punchy"],
		intensity: "high",
	},
	{
		name: "Garage Bump Kick",
		params: { startHz: 140, endHz: 62, decay: 0.34, clickAmount: 0.35 },
		genres: ["uk-garage", "house"],
		characters: ["round", "tight", "warm"],
		intensity: "medium",
	},
	{
		name: "Weighted Bass Kick",
		params: {
			startHz: 130,
			endHz: 44,
			decay: 0.6,
			drive: 2.2,
			noiseTail: 0.25,
		},
		genres: ["dubstep", "drum-and-bass"],
		characters: ["deep", "layered", "distorted"],
		intensity: "high",
	},
	{
		name: "Acoustic Shell Kick",
		params: {
			startHz: 145,
			endHz: 56,
			decay: 0.4,
			noiseTail: 0.65,
			clickAmount: 0.6,
		},
		genres: ["lofi", "breakbeat", "electronic-pop"],
		characters: ["organic", "roomy", "warm"],
		intensity: "low",
	},
	{
		name: "Floor Sub Kick",
		params: {
			startHz: 100,
			endHz: 34,
			decay: 1,
			curve: 0.75,
			clickAmount: 0.04,
		},
		genres: ["dubstep", "ambient", "techno"],
		characters: ["sub-heavy", "deep", "long"],
		intensity: "medium",
	},
	{
		name: "Layered Snap Kick",
		params: {
			startHz: 165,
			endHz: 50,
			decay: 0.4,
			clickAmount: 0.75,
			noiseTail: 0.3,
			drive: 1.6,
		},
		genres: ["drum-and-bass", "techno", "dubstep"],
		characters: ["layered", "punchy", "bright"],
		intensity: "high",
	},
	{
		name: "Overdriven Fold Kick",
		params: { startHz: 170, endHz: 48, decay: 0.38, drive: 14 },
		genres: ["techno", "dubstep"],
		characters: ["distorted", "abrasive", "experimental"],
		intensity: "extreme",
	},
	{
		name: "Roomy Wide Kick",
		params: { startHz: 130, endHz: 50, decay: 0.55, noiseTail: 0.5 },
		genres: ["house", "breakbeat", "electronic-pop"],
		characters: ["roomy", "organic", "round"],
		intensity: "medium",
	},
	{
		name: "Minimal Tick Kick",
		params: { startHz: 145, endHz: 66, decay: 0.12, clickAmount: 0.8 },
		genres: ["techno", "house"],
		characters: ["short", "dry", "tight"],
		intensity: "low",
	},
	{
		name: "Warm Vinyl Kick",
		params: {
			startHz: 118,
			endHz: 49,
			decay: 0.42,
			drive: 1.9,
			clickCutoff: 850,
		},
		genres: ["lofi", "hip-hop", "house"],
		characters: ["warm", "soft", "gritty"],
		intensity: "low",
	},
	{
		name: "High Tuned Kick",
		params: { startHz: 175, endHz: 74, decay: 0.3, clickAmount: 0.45 },
		genres: ["breakbeat", "jungle", "uk-garage"],
		characters: ["tuned", "tight", "bright"],
		intensity: "medium",
	},
	{
		name: "Square Body Kick",
		params: {
			startHz: 135,
			endHz: 46,
			decay: 0.35,
			bodyWaveform: "square",
			drive: 1.5,
		},
		genres: ["techno", "dubstep"],
		characters: ["gritty", "experimental", "dark"],
		intensity: "high",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const SNARES = [
	{
		name: "Tight Studio Snare",
		params: { toneHz: 190, toneDecay: 0.1, noiseDecay: 0.14 },
		genres: ["house", "electronic-pop", "breakbeat"],
		characters: ["tight", "dry", "clean"],
		intensity: "medium",
	},
	{
		name: "Wide Room Snare",
		params: { toneHz: 175, noiseDecay: 0.26, room: 0.4 },
		genres: ["breakbeat", "drum-and-bass", "electronic-pop"],
		characters: ["roomy", "organic", "long"],
		intensity: "medium",
	},
	{
		name: "Dry Rimmed Snare",
		params: { toneHz: 220, toneDecay: 0.07, noiseDecay: 0.09, noiseGain: 0.6 },
		genres: ["hip-hop", "lofi", "uk-garage"],
		characters: ["dry", "short", "tight"],
		intensity: "low",
	},
	{
		name: "Noisy Machine Snare",
		params: {
			toneHz: 205,
			noiseGain: 1.2,
			noiseHighpass: 1200,
			noiseDecay: 0.16,
		},
		genres: ["techno", "electronic-pop"],
		characters: ["noisy", "bright", "dry"],
		intensity: "medium",
	},
	{
		name: "Deep Body Snare",
		params: { toneHz: 155, toneGain: 1, toneDecay: 0.16, noiseDecay: 0.2 },
		genres: ["hip-hop", "trap", "lofi"],
		characters: ["deep", "warm", "round"],
		intensity: "medium",
	},
	{
		name: "Crushed Break Snare",
		params: { toneHz: 210, noiseDecay: 0.19, drive: 5, noiseHighpass: 900 },
		genres: ["drum-and-bass", "jungle", "breakbeat"],
		characters: ["distorted", "gritty", "punchy"],
		intensity: "high",
	},
	{
		name: "Halftime Slab Snare",
		params: {
			toneHz: 165,
			toneDecay: 0.2,
			noiseDecay: 0.3,
			room: 0.3,
			drive: 2,
		},
		genres: ["dubstep", "trap"],
		characters: ["long", "layered", "roomy"],
		intensity: "high",
	},
	{
		name: "Soft Brush Snare",
		params: {
			toneHz: 185,
			toneGain: 0.35,
			noiseGain: 0.7,
			noiseHighpass: 2200,
			noiseDecay: 0.13,
		},
		genres: ["lofi", "ambient", "electronic-pop"],
		characters: ["soft", "organic", "warm"],
		intensity: "low",
	},
	{
		name: "Bright Clap Snare",
		params: {
			toneHz: 240,
			toneGain: 0.4,
			noiseHighpass: 1800,
			noiseLowpass: 12000,
		},
		genres: ["house", "trance", "uk-garage"],
		characters: ["bright", "tight", "clean"],
		intensity: "medium",
	},
	{
		name: "Ghost Tap Snare",
		params: { toneHz: 200, toneDecay: 0.04, noiseDecay: 0.05, noiseGain: 0.5 },
		genres: ["drum-and-bass", "jungle", "breakbeat", "uk-garage"],
		characters: ["short", "soft", "dry"],
		intensity: "low",
	},
	{
		name: "Metal Edge Snare",
		params: { toneHz: 260, toneRatio: 1.93, noiseHighpass: 2600, drive: 3 },
		genres: ["techno", "dubstep"],
		characters: ["metallic", "abrasive", "bright"],
		intensity: "high",
	},
	{
		name: "Dusty Sampler Snare",
		params: { toneHz: 195, noiseLowpass: 5200, drive: 2.4, noiseDecay: 0.12 },
		genres: ["lofi", "hip-hop"],
		characters: ["gritty", "warm", "dark"],
		intensity: "low",
	},
	{
		name: "Rolling Fill Snare",
		params: { toneHz: 230, toneDecay: 0.06, noiseDecay: 0.08, noiseGain: 1 },
		genres: ["drum-and-bass", "trance", "breakbeat", "jungle"],
		characters: ["short", "bright", "tight"],
		intensity: "medium",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const CLAPS = [
	{
		name: "Classic House Clap",
		params: { spread: 0.011, bursts: 4, decay: 0.22, bandHz: 1400 },
		genres: ["house", "uk-garage", "electronic-pop"],
		characters: ["clean", "punchy", "roomy"],
		intensity: "medium",
	},
	{
		name: "Tight Dry Clap",
		params: { spread: 0.006, bursts: 3, decay: 0.11, bandHz: 1800, room: 0.08 },
		genres: ["techno", "trap", "hip-hop"],
		characters: ["tight", "dry", "short"],
		intensity: "medium",
	},
	{
		name: "Wide Hall Clap",
		params: { spread: 0.016, bursts: 5, decay: 0.34, room: 0.55 },
		genres: ["house", "trance", "ambient"],
		characters: ["roomy", "long", "soft"],
		intensity: "low",
	},
	{
		name: "Hard Club Clap",
		params: {
			spread: 0.009,
			bursts: 4,
			decay: 0.2,
			bandHz: 2200,
			q: 1.6,
			room: 0.2,
		},
		genres: ["techno", "trance"],
		characters: ["bright", "punchy", "clean"],
		intensity: "high",
	},
	{
		name: "Low Body Clap",
		params: { bandHz: 900, q: 0.8, decay: 0.26, room: 0.3 },
		genres: ["hip-hop", "lofi", "dubstep"],
		characters: ["warm", "round", "dark"],
		intensity: "medium",
	},
	{
		name: "Loose Hand Clap",
		params: { spread: 0.022, bursts: 5, jitter: 0.8, decay: 0.24, room: 0.35 },
		genres: ["breakbeat", "lofi", "electronic-pop", "jungle"],
		characters: ["organic", "roomy", "soft"],
		intensity: "low",
	},
	{
		name: "Single Slap Clap",
		params: { spread: 0, bursts: 1, decay: 0.16, bandHz: 1600, room: 0.15 },
		genres: ["hip-hop", "trap", "techno"],
		characters: ["short", "dry", "tight"],
		intensity: "medium",
	},
	{
		name: "Layered Stack Clap",
		params: { spread: 0.013, bursts: 7, decay: 0.3, room: 0.4 },
		genres: ["trance", "electronic-pop", "house"],
		characters: ["layered", "long", "clean"],
		intensity: "high",
	},
	{
		name: "Noise Burst Clap",
		params: {
			spread: 0.004,
			bursts: 6,
			decay: 0.13,
			bandHz: 3400,
			q: 0.6,
			room: 0.12,
		},
		genres: ["dubstep", "drum-and-bass", "techno"],
		characters: ["noisy", "abrasive", "bright"],
		intensity: "high",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const RIMS = [
	{
		name: "Dry Rim Click",
		params: { toneHz: 420, decay: 0.05, metal: 0.4 },
		genres: ["house", "hip-hop", "uk-garage"],
		characters: ["dry", "short", "tight"],
		intensity: "low",
	},
	{
		name: "Wooden Rim Knock",
		params: { toneHz: 340, decay: 0.07, metal: 0.15, drive: 1.1 },
		genres: ["lofi", "breakbeat", "electronic-pop"],
		characters: ["wooden", "organic", "soft"],
		intensity: "low",
	},
	{
		name: "Metallic Rim Ping",
		params: { toneHz: 620, decay: 0.09, metal: 1.1, drive: 2 },
		genres: ["techno", "dubstep"],
		characters: ["metallic", "resonant", "bright"],
		intensity: "medium",
	},
	{
		name: "Deep Rim Thud",
		params: { toneHz: 240, decay: 0.06, metal: 0.25 },
		genres: ["hip-hop", "trap", "lofi"],
		characters: ["dark", "round", "dry"],
		intensity: "low",
	},
	{
		name: "Crushed Rim Snap",
		params: { toneHz: 500, decay: 0.04, metal: 0.8, drive: 6 },
		genres: ["techno", "drum-and-bass"],
		characters: ["distorted", "abrasive", "short"],
		intensity: "high",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const CLOSED_HATS = [
	{
		name: "Tight Closed Hat",
		params: { decay: 0.045, highpassHz: 7500 },
		genres: ["house", "techno", "electronic-pop"],
		characters: ["tight", "clean", "short"],
		intensity: "medium",
		choke: "closed",
	},
	{
		name: "Short Tick Hat",
		params: { decay: 0.022, highpassHz: 9000, noise: 0.15 },
		genres: ["techno", "trance", "uk-garage"],
		characters: ["short", "dry", "bright"],
		intensity: "low",
		choke: "closed",
	},
	{
		name: "Airy Closed Hat",
		params: { decay: 0.06, highpassHz: 6000, noise: 0.6 },
		genres: ["house", "lofi", "ambient"],
		characters: ["soft", "noisy", "warm"],
		intensity: "low",
		choke: "closed",
	},
	{
		name: "Dark Closed Hat",
		params: { decay: 0.05, highpassHz: 4500, bandHz: 5200, fundamental: 32 },
		genres: ["techno", "dubstep", "hip-hop"],
		characters: ["dark", "metallic", "dry"],
		intensity: "medium",
		choke: "closed",
	},
	{
		name: "Trap Detail Hat",
		params: { decay: 0.018, highpassHz: 8500, noise: 0.35, drive: 1.4 },
		genres: ["trap", "hip-hop"],
		characters: ["short", "bright", "tight"],
		intensity: "medium",
		choke: "closed",
	},
	{
		name: "Shuffled Garage Hat",
		params: { decay: 0.035, highpassHz: 7000, noise: 0.45, fundamental: 44 },
		genres: ["uk-garage", "house", "breakbeat"],
		characters: ["tight", "noisy", "clean"],
		intensity: "medium",
		choke: "closed",
	},
	{
		name: "Crushed Closed Hat",
		params: { decay: 0.04, highpassHz: 6500, drive: 6, noise: 0.5 },
		genres: ["techno", "drum-and-bass"],
		characters: ["distorted", "abrasive", "gritty"],
		intensity: "high",
		choke: "closed",
	},
	{
		name: "Glassy Closed Hat",
		params: { decay: 0.05, highpassHz: 9500, fundamental: 58, noise: 0.1 },
		genres: ["ambient", "electronic-pop", "trance"],
		characters: ["glassy", "bright", "clean"],
		intensity: "low",
		choke: "closed",
	},
	{
		name: "Pedal Closed Hat",
		params: { decay: 0.075, highpassHz: 5800, noise: 0.4, curve: 1.4 },
		genres: ["breakbeat", "lofi", "hip-hop"],
		characters: ["organic", "soft", "warm"],
		intensity: "low",
		choke: "closed",
	},
	{
		name: "Metallic Tick Hat",
		params: {
			decay: 0.028,
			highpassHz: 8000,
			fundamental: 51,
			ratios: [2, 3.1, 4.7, 6.2, 8.9, 11.4],
		},
		genres: ["techno", "dubstep"],
		characters: ["metallic", "resonant", "short"],
		intensity: "medium",
		choke: "closed",
	},
	{
		name: "Wide Noise Hat",
		params: { decay: 0.055, highpassHz: 7200, noise: 1.1 },
		genres: ["drum-and-bass", "jungle", "breakbeat"],
		characters: ["noisy", "bright", "dry"],
		intensity: "medium",
		choke: "closed",
	},
	{
		name: "Broken Tick Hat",
		params: {
			decay: 0.03,
			highpassHz: 5000,
			fundamental: 23,
			drive: 3,
			noise: 0.2,
		},
		genres: ["techno", "dubstep", "drum-and-bass"],
		characters: ["experimental", "gritty", "dark"],
		intensity: "high",
		choke: "closed",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const OPEN_HATS = [
	{
		name: "Classic Open Hat",
		params: { decay: 0.32, highpassHz: 7000, curve: 1.2 },
		genres: ["house", "techno", "electronic-pop"],
		characters: ["clean", "long", "bright"],
		intensity: "medium",
		choke: "open",
	},
	{
		name: "Short Open Hat",
		params: { decay: 0.16, highpassHz: 7500, curve: 1.4 },
		genres: ["house", "uk-garage"],
		characters: ["tight", "clean", "bright"],
		intensity: "medium",
		choke: "open",
	},
	{
		name: "Long Sizzle Hat",
		params: { decay: 0.62, highpassHz: 6500, noise: 0.7, curve: 1 },
		genres: ["house", "trance", "breakbeat"],
		characters: ["long", "noisy", "bright"],
		intensity: "medium",
		choke: "open",
	},
	{
		name: "Dark Open Hat",
		params: { decay: 0.3, highpassHz: 4200, fundamental: 30, bandHz: 5000 },
		genres: ["techno", "dubstep", "hip-hop"],
		characters: ["dark", "metallic", "dry"],
		intensity: "medium",
		choke: "open",
	},
	{
		name: "Driven Open Hat",
		params: { decay: 0.28, highpassHz: 6800, drive: 5, noise: 0.5 },
		genres: ["techno", "drum-and-bass"],
		characters: ["distorted", "abrasive", "gritty"],
		intensity: "high",
		choke: "open",
	},
	{
		name: "Soft Air Hat",
		params: { decay: 0.4, highpassHz: 5500, noise: 0.9, curve: 0.9 },
		genres: ["lofi", "ambient", "electronic-pop"],
		characters: ["soft", "noisy", "warm"],
		intensity: "low",
		choke: "open",
	},
	{
		name: "Glass Open Hat",
		params: { decay: 0.36, highpassHz: 9000, fundamental: 60, noise: 0.15 },
		genres: ["ambient", "trance", "electronic-pop"],
		characters: ["glassy", "resonant", "bright"],
		intensity: "low",
		choke: "open",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const CYMBALS = [
	{
		name: "Bright Crash Cymbal",
		params: { decay: 2.2, highpassHz: 4500, shimmer: 0.6 },
		genres: ["house", "trance", "electronic-pop"],
		characters: ["bright", "long", "clean"],
		intensity: "high",
	},
	{
		name: "Dark Crash Cymbal",
		params: { decay: 2, fundamental: 28, highpassHz: 3000, shimmer: 0.35 },
		genres: ["techno", "dubstep", "drum-and-bass"],
		characters: ["dark", "metallic", "long"],
		intensity: "high",
	},
	{
		name: "Tight Ride Cymbal",
		params: {
			decay: 0.9,
			fundamental: 46,
			highpassHz: 6000,
			shimmer: 0.3,
			room: 0.1,
		},
		genres: ["house", "breakbeat", "drum-and-bass"],
		characters: ["tight", "metallic", "dry"],
		intensity: "medium",
	},
	{
		name: "Washy Ride Cymbal",
		params: {
			decay: 1.8,
			fundamental: 42,
			highpassHz: 5000,
			shimmer: 0.85,
			room: 0.3,
		},
		genres: ["drum-and-bass", "jungle", "breakbeat"],
		characters: ["noisy", "long", "roomy"],
		intensity: "medium",
	},
	{
		name: "Short Splash Cymbal",
		params: { decay: 0.55, fundamental: 52, highpassHz: 7000, shimmer: 0.5 },
		genres: ["house", "uk-garage", "electronic-pop"],
		characters: ["short", "bright", "clean"],
		intensity: "medium",
	},
	{
		name: "Bell Ride Cymbal",
		params: {
			decay: 1.4,
			fundamental: 64,
			ratios: [2, 2.9, 4.1, 5.2, 7.3, 9.1],
			highpassHz: 4000,
			shimmer: 0.2,
		},
		genres: ["house", "trance", "ambient"],
		characters: ["resonant", "metallic", "tuned"],
		intensity: "medium",
	},
	{
		name: "Trashy Metal Cymbal",
		params: {
			decay: 1.6,
			fundamental: 33,
			ratios: [1.7, 2.3, 3.9, 6.1, 9.4, 13.7],
			highpassHz: 3500,
			shimmer: 0.7,
		},
		genres: ["techno", "dubstep"],
		characters: ["abrasive", "metallic", "experimental"],
		intensity: "extreme",
	},
	{
		name: "Reverse-Ready Swell Cymbal",
		params: {
			decay: 2.6,
			fundamental: 40,
			highpassHz: 4200,
			shimmer: 0.75,
			room: 0.35,
		},
		genres: ["trance", "ambient", "electronic-pop"],
		characters: ["long", "noisy", "roomy"],
		intensity: "medium",
	},
	{
		name: "Lofi Dusty Cymbal",
		params: {
			decay: 1.1,
			fundamental: 36,
			highpassHz: 3200,
			shimmer: 0.4,
			room: 0.25,
		},
		genres: ["lofi", "hip-hop"],
		characters: ["dark", "warm", "gritty"],
		intensity: "low",
	},
];

/** @type {import("./index.mjs").CatalogEntry[]} */
export const TOMS = [
	{
		name: "Low Tuned Tom",
		params: { note: "F2", decay: 0.6 },
		genres: ["techno", "house", "breakbeat"],
		characters: ["tuned", "deep", "round"],
		intensity: "medium",
	},
	{
		name: "Mid Tuned Tom",
		params: { note: "C3", decay: 0.5 },
		genres: ["techno", "house", "breakbeat"],
		characters: ["tuned", "round", "dry"],
		intensity: "medium",
	},
	{
		name: "High Tuned Tom",
		params: { note: "G3", decay: 0.38 },
		genres: ["techno", "drum-and-bass", "breakbeat"],
		characters: ["tuned", "tight", "bright"],
		intensity: "medium",
	},
	{
		name: "Deep Floor Tom",
		params: { note: "C2", decay: 0.85, bendRatio: 2.2, noise: 0.2 },
		genres: ["dubstep", "techno", "ambient"],
		characters: ["deep", "long", "sub-heavy"],
		intensity: "medium",
	},
	{
		name: "Driven Industrial Tom",
		params: { note: "A2", decay: 0.45, drive: 5, noise: 0.25 },
		genres: ["techno", "dubstep"],
		characters: ["distorted", "abrasive", "dark"],
		intensity: "high",
	},
	{
		name: "Soft Skin Tom",
		params: { note: "D3", decay: 0.42, noise: 0.35, bendRatio: 1.5 },
		genres: ["lofi", "breakbeat", "electronic-pop"],
		characters: ["organic", "soft", "warm"],
		intensity: "low",
	},
	{
		name: "Snappy Roll Tom",
		params: { note: "E3", decay: 0.24, bendRatio: 2.4, noise: 0.2 },
		genres: ["drum-and-bass", "jungle", "trance"],
		characters: ["short", "tight", "punchy"],
		intensity: "medium",
	},
	{
		name: "Detuned Wobble Tom",
		params: { note: "G2", decay: 0.7, bendRatio: 3.2, noise: 0.15 },
		genres: ["dubstep", "techno"],
		characters: ["experimental", "tuned", "dark"],
		intensity: "high",
	},
];

/**
 * Conventional and found/experimental percussion. Sections 6.2 and 6.4 both
 * push hard here: hand percussion and tuned wood/metal alongside glass, stone,
 * mechanical and glitched material that resists categorisation.
 *
 * @type {import("./index.mjs").CatalogEntry[]}
 */
export const PERCUSSION = [
	{
		name: "Open Conga",
		voice: "membrane",
		params: { note: "A2", decay: 0.4, slap: 0.35 },
		genres: ["house", "breakbeat", "electronic-pop"],
		characters: ["organic", "warm", "tuned"],
		intensity: "medium",
	},
	{
		name: "Slap Conga",
		voice: "membrane",
		params: { note: "D3", decay: 0.22, slap: 0.9, bendRatio: 1.6 },
		genres: ["house", "uk-garage", "breakbeat"],
		characters: ["organic", "punchy", "short"],
		intensity: "medium",
	},
	{
		name: "Low Bongo",
		voice: "membrane",
		params: { note: "A3", decay: 0.25, slap: 0.5, tone: 1.9 },
		genres: ["house", "lofi", "electronic-pop"],
		characters: ["organic", "warm", "tuned"],
		intensity: "low",
	},
	{
		name: "High Bongo",
		voice: "membrane",
		params: { note: "E4", decay: 0.18, slap: 0.6, tone: 2.1 },
		genres: ["house", "lofi", "electronic-pop"],
		characters: ["organic", "bright", "short"],
		intensity: "low",
	},
	{
		name: "Close Shaker",
		voice: "shaker",
		params: { decay: 0.08, bandHz: 6500 },
		genres: ["house", "hip-hop", "electronic-pop"],
		characters: ["organic", "dry", "short"],
		intensity: "low",
	},
	{
		name: "Long Shaker",
		voice: "shaker",
		params: { decay: 0.19, bandHz: 5200, grains: 1200, curve: 1 },
		genres: ["house", "lofi", "breakbeat"],
		characters: ["organic", "soft", "long"],
		intensity: "low",
	},
	{
		name: "Bright Cabasa",
		voice: "shaker",
		params: { decay: 0.1, bandHz: 9000, q: 2.2, grains: 1800 },
		genres: ["house", "uk-garage", "trance"],
		characters: ["bright", "organic", "tight"],
		intensity: "medium",
	},
	{
		name: "Wood Block",
		voice: "struck",
		params: { material: "wood", note: "A4", decay: 0.16 },
		genres: ["house", "techno", "breakbeat"],
		characters: ["wooden", "dry", "short"],
		intensity: "low",
	},
	{
		name: "Deep Wood Knock",
		voice: "struck",
		params: { material: "wood", note: "C3", decay: 0.3, noise: 1.3 },
		genres: ["lofi", "hip-hop", "ambient"],
		characters: ["wooden", "organic", "warm"],
		intensity: "low",
	},
	{
		name: "Claves",
		voice: "struck",
		params: { material: "wood", note: "E5", decay: 0.11, brightness: 1.3 },
		genres: ["house", "electronic-pop", "uk-garage"],
		characters: ["wooden", "bright", "short"],
		intensity: "low",
	},
	{
		name: "Cowbell",
		voice: "struck",
		params: { material: "metal", note: "G4", decay: 0.28, noise: 0.6 },
		genres: ["house", "techno", "electronic-pop"],
		characters: ["metallic", "resonant", "tuned"],
		intensity: "medium",
	},
	{
		name: "Agogo Bell",
		voice: "struck",
		params: { material: "metal", note: "C5", decay: 0.34, brightness: 1.2 },
		genres: ["house", "breakbeat", "electronic-pop"],
		characters: ["metallic", "tuned", "bright"],
		intensity: "medium",
	},
	{
		name: "Struck Metal Plate",
		voice: "struck",
		params: { material: "metal", note: "D3", decay: 1.2, noise: 0.8 },
		genres: ["techno", "dubstep", "ambient"],
		characters: ["metallic", "resonant", "experimental"],
		intensity: "high",
	},
	{
		name: "Scrap Metal Hit",
		voice: "struck",
		params: {
			material: "metal",
			note: "F2",
			decay: 0.7,
			brightness: 1.8,
			noise: 1.6,
		},
		genres: ["techno", "dubstep", "drum-and-bass"],
		characters: ["abrasive", "metallic", "experimental"],
		intensity: "extreme",
	},
	{
		name: "Anvil Ping",
		voice: "struck",
		params: {
			material: "metal",
			note: "A5",
			decay: 0.5,
			brightness: 2,
			noise: 0.4,
		},
		genres: ["techno", "drum-and-bass"],
		characters: ["metallic", "bright", "experimental"],
		intensity: "high",
	},
	{
		name: "Glass Tap",
		voice: "struck",
		params: { material: "glass", note: "E5", decay: 0.6 },
		genres: ["ambient", "lofi", "electronic-pop"],
		characters: ["glassy", "resonant", "bright"],
		intensity: "low",
	},
	{
		name: "Glass Bowl Ring",
		voice: "struck",
		params: { material: "glass", note: "B4", decay: 1.6, noise: 0.4 },
		genres: ["ambient", "trance", "electronic-pop"],
		characters: ["glassy", "long", "resonant"],
		intensity: "low",
	},
	{
		name: "Cracked Glass Shard",
		voice: "struck",
		params: {
			material: "glass",
			note: "G5",
			decay: 0.3,
			brightness: 2.2,
			noise: 2,
		},
		genres: ["dubstep", "techno", "ambient"],
		characters: ["abrasive", "experimental", "glassy"],
		intensity: "high",
	},
	{
		name: "Stone Knock",
		voice: "struck",
		params: { material: "stone", note: "D3", decay: 0.2 },
		genres: ["hip-hop", "ambient", "lofi"],
		characters: ["organic", "dry", "dark"],
		intensity: "low",
	},
	{
		name: "Heavy Stone Drop",
		voice: "struck",
		params: {
			material: "stone",
			note: "F2",
			decay: 0.42,
			noise: 1.6,
			brightness: 0.7,
		},
		genres: ["dubstep", "techno", "ambient"],
		characters: ["organic", "dark", "experimental"],
		intensity: "medium",
	},
	{
		name: "Mechanical Latch",
		voice: "glitch",
		params: { duration: 0.16, slices: 4, bits: 7, downsample: 3, bandHz: 3200 },
		genres: ["techno", "dubstep", "drum-and-bass"],
		characters: ["experimental", "gritty", "short"],
		intensity: "medium",
	},
	{
		name: "Circuit Percussion Hit",
		voice: "glitch",
		params: {
			duration: 0.22,
			slices: 6,
			bits: 4,
			downsample: 8,
			bandHz: 1800,
			fold: 1.6,
		},
		genres: ["techno", "dubstep"],
		characters: ["experimental", "abrasive", "distorted"],
		intensity: "high",
	},
	{
		name: "Bent Tine Percussion",
		voice: "bell",
		params: { note: "C4", decay: 0.5, index: 9, ratio: 2.37, strike: 0.5 },
		genres: ["ambient", "techno", "electronic-pop"],
		characters: ["metallic", "experimental", "resonant"],
		intensity: "medium",
	},
	{
		name: "Folded Noise Percussion",
		voice: "noiseTexture",
		params: {
			duration: 0.2,
			bandHz: 2400,
			q: 3.5,
			rate: 40,
			depth: 1,
			crush: 4,
			drive: 3,
		},
		genres: ["dubstep", "techno", "drum-and-bass"],
		characters: ["abrasive", "experimental", "noisy"],
		intensity: "extreme",
	},
];
