/**
 * The deterministic half of the scheduled QA sweep (#859).
 *
 * `.github/workflows/qa-sweep.yml` sends a few agents at the live app, one per
 * core flow. The agents explore and *report*; they never write to Linear. Every
 * rule that has to hold however an agent behaves lives here, as pure functions
 * with tests beside them:
 *
 *   - which flows a run covers, and how many agents it may start;
 *   - what counts as a well-formed finding;
 *   - which findings become new issues, which are an issue seen again, and
 *     which fall over the per-run issue cap;
 *   - the text of every issue, comment and run summary the sweep writes.
 *
 * `plan.mjs` and `file.mjs` are the thin command-line ends that do the I/O.
 */

import * as nodeFs from "node:fs";
import { join } from "node:path";

/** The spec's defaults (#859): five agents and fifteen new issues a run. */
export const DEFAULT_AGENTS = 5;
export const DEFAULT_ISSUES = 15;

/**
 * Hard ceilings a configured limit is clamped to. A typo in a repository
 * variable (`50` agents, `500` issues) must not become a run that floods the
 * tracker or burns a week of agent budget.
 *
 * Each agent signs in as its own QA account, and the pool has one per agent up
 * to this ceiling (`MAX_QA_SLOT` in `src/access/qaAccounts.ts`, #1055): raising
 * it means adding accounts there and running `bun run qa:accounts` first.
 */
export const MAX_AGENTS = 10;
export const MAX_ISSUES = 50;

/** The label on the Linear issue that carries each run's summary. */
export const LOG_LABEL = "qa-sweep";
export const LOG_TITLE = "QA sweep";

/** The branch `scripts/walkthrough/publish.mjs` pushes screenshots to. */
export const WALKTHROUGH_BRANCH = "claude/walkthroughs";

const FOOTER = "---\n_Generated by [Claude Code](https://claude.ai/code)_";

/** Longest a single text field of a finding may be before it is cut. */
const MAX_FIELD = 4000;
const MAX_TITLE = 120;
const MAX_STEPS = 30;

/**
 * Longest body the sweep posts. A long finding is cut well short of what an
 * issue or comment may hold, rather than lost.
 */
export const MAX_BODY = 60000;

const SEVERITIES = ["high", "medium", "low"];

/**
 * Agent-written text with every `@mention` broken by a zero-width space. It is
 * pasted into issues and comments the sweep posts with a write token: a
 * verbatim `@claude` would start a Claude run on it (board.yml's poll), and
 * `@someone` would ping them. The text reads the same; it is just no longer a
 * mention.
 */
export function neutralizeMentions(value) {
  return value.replace(/@(?=[A-Za-z0-9_-])/g, "@\u200b");
}

/** A body cut to `MAX_BODY`, saying so, with the footer kept. */
export function capBody(body, max = MAX_BODY) {
  if (body.length <= max) return body;
  const note = `\n\n_…cut to ${max} characters: see the run's artifacts for the rest._\n\n${FOOTER}`;
  return body.slice(0, max - note.length) + note;
}

/**
 * A limit from the first source that sets one, in precedence order (the
 * dispatch input, then the repository variable), else the default. Blank
 * means "not set"; anything else must be a whole number at least `min`, and is
 * clamped to `ceiling`.
 */
export function resolveLimit(sources, { fallback, ceiling, min = 0, name = "limit" }) {
  for (const raw of sources) {
    if (raw === undefined || raw === null) continue;
    const text = String(raw).trim();
    if (text === "") continue;
    const value = Number(text);
    if (!/^\d+$/.test(text) || value < min)
      throw new Error(`${name}: "${text}" is not a whole number of at least ${min}.`);
    return Math.min(value, ceiling);
  }
  return fallback;
}

const FLOW_HEADING = /^### (CF-\d{3}) — (.+)$/gm;

/** The same comment stripping `scripts/check-core-flows.mjs` does, for the same reason. */
const stripComments = (source) =>
  source.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:])\/\/.*$/gm, "$1");

/**
 * The flows registered in `docs/core-flows.md`, in register order. `specs`
 * maps a flow ID to its spec's source; a flow whose spec still calls
 * `test.fixme` is `parked`: it describes work in flight, so the live app not
 * doing all of it yet is not a bug.
 */
export function parseFlows(register, specs = new Map()) {
  const flows = [];
  for (const [, id, title] of register.matchAll(FLOW_HEADING)) {
    if (flows.some((f) => f.id === id)) continue;
    const spec = specs.get(id);
    flows.push({
      id,
      title: title.trim(),
      parked: spec ? /\.fixme\s*\(/.test(stripComments(spec)) : false,
    });
  }
  return flows;
}

const WEEK_MS = 7 * 24 * 60 * 60 * 1000;

/**
 * Which flows this run walks: the ones asked for by ID, or else the next
 * `count` in a weekly rotation through the register, so successive weekly runs
 * cover every flow rather than the first five forever.
 */
export function pickFlows({ flows, count, date, requested = [] }) {
  if (flows.length === 0) throw new Error("docs/core-flows.md registers no flows.");
  const byId = new Map(flows.map((f) => [f.id, f]));
  if (requested.length > 0) {
    const unknown = requested.filter((id) => !byId.has(id));
    if (unknown.length > 0)
      throw new Error(`Not registered in docs/core-flows.md: ${unknown.join(", ")}.`);
    return [...new Set(requested)].slice(0, count).map((id) => byId.get(id));
  }
  const ordered = [...flows].sort((a, b) => a.id.localeCompare(b.id));
  const take = Math.min(count, ordered.length);
  const week = Math.floor(date.getTime() / WEEK_MS);
  const start = (week * take) % ordered.length;
  return Array.from({ length: take }, (_, i) => ordered[(start + i) % ordered.length]);
}

/** `"CF-001, cf-2"` → `["CF-001", "CF-002"]`. */
export function parseFlowList(text) {
  if (!text) return [];
  return text
    .split(/[\s,]+/)
    .filter(Boolean)
    .map((token) => {
      const match = token.match(/^cf-?(\d{1,3})$/i);
      if (!match) throw new Error(`"${token}" is not a flow ID like CF-007.`);
      return `CF-${match[1].padStart(3, "0")}`;
    });
}

const text = (value, field, problems) => {
  if (typeof value !== "string" || value.trim() === "") {
    problems.push(`${field} is missing`);
    return "";
  }
  const trimmed = neutralizeMentions(value.trim());
  return trimmed.length > MAX_FIELD ? `${trimmed.slice(0, MAX_FIELD)}…` : trimmed;
};

/**
 * A screenshot path is relative to the agent's output directory and must stay
 * inside it: the filing job copies whatever it names into a public branch.
 */
export function isSafeScreenshotPath(path) {
  return (
    typeof path === "string" &&
    /\.png$/i.test(path) &&
    !path.startsWith("/") &&
    !path.includes("\\") &&
    !path.split("/").some((part) => part === ".." || part === "")
  );
}

/**
 * One finding as an agent wrote it, checked and normalised. Returns
 * `{ finding }` or `{ problems }`; never a half-valid finding.
 */
export function validateFinding(raw) {
  const problems = [];
  if (!raw || typeof raw !== "object" || Array.isArray(raw))
    return { problems: ["is not an object"] };

  let title = text(raw.title, "title", problems);
  if (title && !/^Bug: \S/.test(title))
    problems.push('title does not start with "Bug: "');
  if (title.length > MAX_TITLE) title = `${title.slice(0, MAX_TITLE - 1)}…`;
  const symptom = text(raw.symptom, "symptom", problems);
  const expected = text(raw.expected, "expected", problems);

  let steps = [];
  if (!Array.isArray(raw.steps) || raw.steps.length === 0)
    problems.push("steps is missing");
  else if (raw.steps.some((s) => typeof s !== "string" || s.trim() === ""))
    problems.push("steps has an empty step");
  else
    steps = raw.steps
      .slice(0, MAX_STEPS)
      .map((s) => neutralizeMentions(s.trim()).slice(0, MAX_FIELD));

  const severity = raw.severity ?? "medium";
  if (!SEVERITIES.includes(severity))
    problems.push(`severity is not one of ${SEVERITIES.join(", ")}`);

  const screenshot = raw.screenshot ?? null;
  if (screenshot !== null && !isSafeScreenshotPath(screenshot))
    problems.push("screenshot is not a .png path inside the output directory");

  let duplicateOf = raw.duplicateOf ?? null;
  if (duplicateOf !== null && !isIssueId(duplicateOf))
    problems.push("duplicateOf is not an issue identifier like GRV-12");
  else if (duplicateOf !== null) duplicateOf = duplicateOf.toUpperCase();

  if (problems.length > 0) return { problems };
  return {
    finding: { title, symptom, expected, steps, severity, screenshot, duplicateOf },
  };
}

/** A Linear identifier: a team key, a dash, a number. */
export const isIssueId = (value) =>
  typeof value === "string" && /^[A-Za-z][A-Za-z0-9]*-\d+$/.test(value);

/**
 * One agent's `findings.json`, parsed. A report that is not JSON, or not the
 * expected shape, is a failed agent, not zero findings: the summary has to
 * tell those apart.
 */
export function readReport(json, flow) {
  let raw;
  try {
    raw = JSON.parse(json);
  } catch {
    return { flow, ok: false, error: "findings.json is not valid JSON", findings: [] };
  }
  if (!raw || typeof raw !== "object" || !Array.isArray(raw.findings))
    return {
      flow,
      ok: false,
      error: "findings.json has no findings array",
      findings: [],
    };
  const findings = [];
  const rejected = [];
  raw.findings.forEach((entry, index) => {
    const { finding, problems } = validateFinding(entry);
    if (finding) findings.push({ ...finding, flow });
    else rejected.push({ flow, index, problems });
  });
  const notes =
    typeof raw.notes === "string"
      ? neutralizeMentions(raw.notes.trim()).slice(0, 600)
      : "";
  return { flow, ok: true, findings, rejected, notes };
}

/** A title reduced to its words, for spotting the same bug filed twice. */
export function normalizeTitle(title) {
  return title
    .replace(/^\s*bug\s*:\s*/i, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

const severityRank = (s) => SEVERITIES.indexOf(s);

/**
 * Decide what the run writes. Findings are taken most severe first (then by
 * flow, then in the order the agent reported them), so when the cap bites it
 * is the minor findings that wait for next week.
 *
 *   - A finding that names an open issue as `duplicateOf`, or whose title
 *     matches an open issue's, is that issue **re-seen**: a comment, never a
 *     new issue, and it does not count towards the cap.
 *   - Two agents reporting the same title in one run make one issue.
 *   - Everything else is **filed** until `maxIssues` is reached, then
 *     **overCap**: listed in the summary, not filed.
 */
export function planFiling({ findings, openIssues, maxIssues }) {
  const open = new Map(openIssues.map((issue) => [issue.id, issue]));
  const openByTitle = new Map();
  for (const issue of openIssues) {
    const key = normalizeTitle(issue.title);
    if (key && !openByTitle.has(key)) openByTitle.set(key, issue);
  }

  const ordered = findings
    .map((finding, order) => ({ finding, order }))
    .sort(
      (a, b) =>
        severityRank(a.finding.severity) - severityRank(b.finding.severity) ||
        a.finding.flow.localeCompare(b.finding.flow) ||
        a.order - b.order,
    )
    .map(({ finding }) => finding);

  const file = [];
  const overCap = [];
  const reseen = new Map();
  const thisRun = new Map();

  for (const finding of ordered) {
    const key = normalizeTitle(finding.title);
    const match =
      (finding.duplicateOf !== null && open.get(finding.duplicateOf)) ||
      openByTitle.get(key);
    if (match) {
      if (!reseen.has(match.id))
        reseen.set(match.id, {
          id: match.id,
          title: match.title,
          findings: [],
        });
      reseen.get(match.id).findings.push(finding);
      continue;
    }
    const twin = thisRun.get(key);
    if (twin) {
      if (!twin.alsoSeenIn.includes(finding.flow) && twin.flow !== finding.flow)
        twin.alsoSeenIn.push(finding.flow);
      continue;
    }
    const entry = { ...finding, alsoSeenIn: [] };
    thisRun.set(key, entry);
    if (file.length < maxIssues) file.push(entry);
    else overCap.push(entry);
  }

  return { file, reseen: [...reseen.values()], overCap };
}

/**
 * The raw URL `scripts/walkthrough/publish.mjs` publishes an image at. Kept to
 * one short directory per image (`<run>-<n>/1.png`) so every URL stays well
 * under the 150 characters past which an agent environment breaks the link.
 */
export function screenshotUrl({ repo, issue, id, file = "1.png" }) {
  return `https://raw.githubusercontent.com/${repo}/refs/heads/${WALKTHROUGH_BRANCH}/${issue}/${id}/${file}`;
}

const flowLabel = (flow, flows) => {
  const known = flows?.find((f) => f.id === flow);
  return known ? `${flow} (${known.title})` : flow;
};

const environmentLine = ({ siteUrl, build }) =>
  `${siteUrl}, build \`${build || "unknown"}\`, Chromium (Playwright, headless, 1280×720), signed in as one of the sweep's QA accounts.`;

/** The body of a new `Bug: …` issue. */
export function issueBody(finding, ctx) {
  const seenIn = [finding.flow, ...finding.alsoSeenIn]
    .map((f) => flowLabel(f, ctx.flows))
    .join(", ");
  const lines = [
    `**Symptom:** ${finding.symptom}`,
    "",
    `**Expected:** ${finding.expected}`,
    "",
    "**Steps to reproduce:**",
    "",
    ...finding.steps.map((step, i) => `${i + 1}. ${step}`),
    "",
    `**Environment:** ${environmentLine(ctx)}`,
    "",
    `**Found by:** the scheduled QA sweep ([run](${ctx.runUrl})) while walking ${seenIn}. Severity as the agent judged it: ${finding.severity}.`,
    "",
  ];
  if (finding.screenshotUrl)
    lines.push(
      "**Screenshot:**",
      "",
      `![${finding.flow} finding](${finding.screenshotUrl})`,
      "",
    );
  lines.push(FOOTER);
  return capBody(lines.join("\n"));
}

/** The comment on an open issue a run saw again. */
export function reseenComment(entry, ctx) {
  const lines = [
    `**Seen again by the QA sweep** ([run](${ctx.runUrl})).`,
    "",
    `**Environment:** ${environmentLine(ctx)}`,
    "",
  ];
  for (const finding of entry.findings) {
    lines.push(
      `While walking ${flowLabel(finding.flow, ctx.flows)}: ${finding.symptom}`,
      "",
      ...finding.steps.map((step, i) => `${i + 1}. ${step}`),
      "",
    );
    if (finding.screenshotUrl)
      lines.push(`![${finding.flow} finding](${finding.screenshotUrl})`, "");
  }
  lines.push(FOOTER);
  return capBody(lines.join("\n"));
}

/** The body the log issue is created with. */
export function logIssueBody() {
  return [
    "The scheduled QA sweep (`.github/workflows/qa-sweep.yml`) posts a summary of every run here: the flows it walked, the bugs it filed, and the open bugs it saw again.",
    "",
    'Agents walk core flows from `docs/core-flows.md` in the live app, each signed in as its own QA account, file each new bug as a `Bug: …` issue, and delete the projects they made before the run ends. See `docs/testing.md`, "Scheduled QA sweep".',
    "",
    "This is a record, not a card: leave it in Backlog with its `qa-sweep` label (the board automation ignores it). The sweep finds it by that label, and makes a new one if it is marked Done or Canceled.",
    "",
    FOOTER,
  ].join("\n");
}

const AGENT_STATE = {
  ok: "walked",
  failed: "**agent failed**",
  missing: "**no report**",
};

/** The run summary posted on the log issue. */
export function summaryBody({
  date,
  runUrl,
  build,
  limits,
  flows,
  reports,
  filed,
  reseen,
  overCap,
  cleanup,
  failures = [],
  dryRun = false,
}) {
  const reportFor = (id) => reports.find((r) => r.flow === id);
  const lines = [
    `## QA sweep, ${date}${dryRun ? " (dry run: nothing was filed)" : ""}`,
    "",
    `[Run](${runUrl}) against build \`${build || "unknown"}\`. Limits: ${limits.agents} agents, ${limits.issues} new issues.`,
    "",
    `### Flows covered (${flows.length})`,
    "",
    "| Flow | Agent | Findings | Projects cleaned up |",
    "| --- | --- | --- | --- |",
  ];
  for (const flow of flows) {
    const report = reportFor(flow.id);
    const state = !report ? "missing" : report.ok ? "ok" : "failed";
    const clean = cleanup.find((c) => c.flow === flow.id);
    const cleaned = !clean
      ? "**unknown**"
      : clean.ok
        ? `yes (${clean.deleted})`
        : `**no** (${clean.remaining ?? "?"} left)`;
    const found = report?.ok ? String(report.findings.length) : "–";
    const parked = flow.parked ? " _(parked)_" : "";
    lines.push(
      `| ${flow.id} ${flow.title}${parked} | ${AGENT_STATE[state]} | ${found} | ${cleaned} |`,
    );
  }
  const notes = reports.filter((r) => r.notes || r.error);
  if (notes.length > 0) {
    lines.push("");
    for (const r of notes) lines.push(`- **${r.flow}:** ${r.error ?? r.notes}`);
  }

  const list = (items, render) => (items.length ? items.map(render) : ["None."]);
  lines.push(
    "",
    `### Issues filed (${filed.length})`,
    "",
    ...list(
      filed,
      (f) =>
        `- ${f.id ? f.id : f.title} (${f.flow})${f.failed ? " **not filed: the write failed**" : ""}`,
    ),
    "",
    `### Issues re-seen (${reseen.length})`,
    "",
    ...list(reseen, (r) => `- ${r.id} (${r.findings.map((f) => f.flow).join(", ")})`),
  );
  if (overCap.length > 0)
    lines.push(
      "",
      `### Not filed: over the cap of ${limits.issues} (${overCap.length})`,
      "",
      ...overCap.map((f) => `- ${f.title} (${f.flow}, ${f.severity})`),
    );
  const rejected = reports.flatMap((r) => r.rejected ?? []);
  if (rejected.length > 0)
    lines.push(
      "",
      `### Malformed findings dropped (${rejected.length})`,
      "",
      ...rejected.map((r) => `- ${r.flow} #${r.index + 1}: ${r.problems.join("; ")}`),
    );
  if (failures.length > 0)
    lines.push(
      "",
      `### Linear writes that failed (${failures.length})`,
      "",
      ...failures.map((f) => `- ${f.what}: ${f.error}`),
    );
  lines.push("", FOOTER);
  return capBody(lines.join("\n"));
}

/**
 * Do the run's Linear writes: each new issue, then each re-seen comment.
 * `write.create({ title, body })` returns the new issue's `{ id }` (its
 * identifier) and `write.comment(id, body)` posts on an issue; one that throws
 * (a rate limit, a 5xx, a body Linear refuses) is recorded and the rest still
 * go, so a single bad write never costs the other findings or the summary.
 *
 * Returns the failures, each `{ what, error }`, for the summary.
 */
export async function fileFindings({
  plan,
  ctx,
  write,
  dryRun = false,
  log = console.log,
}) {
  const failures = [];
  const attempt = async (what, job) => {
    try {
      await job();
      return true;
    } catch (error) {
      failures.push({ what, error: describeError(error) });
      return false;
    }
  };
  for (const finding of plan.file) {
    const body = issueBody(finding, ctx);
    if (dryRun) {
      log(`\n=== would file: ${finding.title}\n${body}`);
      continue;
    }
    const ok = await attempt(`filing "${finding.title}"`, async () => {
      finding.id = (await write.create({ title: finding.title, body })).id;
    });
    if (ok) log(`Filed ${finding.id}: ${finding.title}`);
    else finding.failed = true;
  }
  for (const entry of plan.reseen) {
    const body = reseenComment(entry, ctx);
    if (dryRun) {
      log(`\n=== would comment on ${entry.id}\n${body}`);
      continue;
    }
    if (await attempt(`commenting on ${entry.id}`, () => write.comment(entry.id, body)))
      log(`Commented on ${entry.id}: seen again.`);
  }
  return failures;
}

/** One line of an error, for the summary: no stack, no multi-line output. */
export function describeError(error) {
  const message = error instanceof Error ? error.message : String(error);
  const line = message.split("\n").find((l) => l.trim() !== "") ?? "unknown error";
  return neutralizeMentions(line.trim()).slice(0, 300);
}

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

/**
 * The screenshot a finding names, as a path safe to publish, or `null`. The
 * file must be a regular file (not a symlink), resolve inside `dir` through
 * no symlinked directory, and start with the PNG signature: whatever it is
 * gets pushed to a public branch.
 */
export function resolveScreenshot(dir, relative, fs = nodeFs) {
  if (!isSafeScreenshotPath(relative)) return null;
  try {
    const root = fs.realpathSync(dir);
    const source = join(root, relative);
    const stat = fs.lstatSync(source);
    if (!stat.isFile()) return null;
    if (fs.realpathSync(source) !== source) return null;
    const head = Buffer.alloc(PNG_SIGNATURE.length);
    const fd = fs.openSync(source, "r");
    try {
      fs.readSync(fd, head, 0, head.length, 0);
    } finally {
      fs.closeSync(fd);
    }
    return PNG_SIGNATURE.every((byte, i) => head[i] === byte) ? source : null;
  } catch {
    return null;
  }
}
