#!/usr/bin/env bash
# Generated by scripts/sync-issue-dependencies.mjs -- do not edit by hand.
# Regenerate with: bun run issues:deps -- --emit-sh scripts/create-issue-dependencies.sh
#
# Creates 101 "blocked by" dependencies on GitHub issues, derived from
# the Dependencies: lines and the issue index in docs/backlog.md.
#
# Usage:
#   ./scripts/create-issue-dependencies.sh            # dry run, prints what it would do
#   ./scripts/create-issue-dependencies.sh --apply    # create the dependencies
#
# Requires the GitHub CLI, authenticated: gh auth login
#
# Not created, because these tasks have no issue to point at:
#   FND-001b (task has no issue)
#   FND-001c (task has no issue)
#   FND-002 (task has no issue)
#   FND-002b -> FND-002 (dependency has no issue)
#   FND-003 (task has no issue)
#   FND-004 (task has no issue)
#   FND-005 (task has no issue)
#   FND-006 (task has no issue)
#   FND-007 (task has no issue)
#   FND-008 (task has no issue)
#   CNT-000 (task has no issue)
#   CNT-000b -> CNT-000 (dependency has no issue)
#   FND-009 -> FND-001c (dependency has no issue)
#   FND-009 -> FND-003 (dependency has no issue)
#   FND-009 -> FND-004 (dependency has no issue)
#   FND-009 -> FND-005 (dependency has no issue)
#   FND-009 -> FND-007 (dependency has no issue)
#   FND-009 -> FND-008 (dependency has no issue)
#   ARR-001 -> FND-008 (dependency has no issue)

set -euo pipefail

OWNER=afternoon
REPO=solid-groove
APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

command -v gh >/dev/null || { echo "gh is not installed: https://cli.github.com" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not authenticated: run 'gh auth login'" >&2; exit 1; }

# The API takes a dependency's numeric id, so map issue number -> id up front.
declare -A ID
# Counted explicitly: ${#ID[@]} on an empty array trips 'set -u' on bash < 4.4.
known=0
while IFS=$'\t' read -r number id; do
  ID[$number]=$id
  known=$((known + 1))
done < <(gh api "/repos/$OWNER/$REPO/issues?state=all&per_page=100" --paginate \
           --jq '.[] | select(.pull_request | not) | [.number, .id] | @tsv')

if [ "$known" -eq 0 ]; then
  echo "Could not read issues from $OWNER/$REPO. Check 'gh auth status' and repo access." >&2
  exit 1
fi

added=0; present=0; failed=0

edge() {
  local blocked=$1 blocker=$2 label=$3
  local blocker_id="${ID[$blocker]:-}"

  if [ -z "$blocker_id" ]; then
    echo "  ?? #$blocked  $label -- issue #$blocker not found, skipping" >&2
    failed=$((failed + 1)); return
  fi

  # Idempotent: adding an edge that already exists would be an error.
  if gh api "/repos/$OWNER/$REPO/issues/$blocked/dependencies/blocked_by" \
       --jq '.[].number' 2>/dev/null | grep -qx "$blocker"; then
    present=$((present + 1)); return
  fi

  if [ "$APPLY" = "0" ]; then
    echo "  would add  #$blocked blocked by #$blocker  ($label)"
    added=$((added + 1)); return
  fi

  # -F, not -f: issue_id must go over the wire as a JSON number, not a string.
  if gh api --method POST "/repos/$OWNER/$REPO/issues/$blocked/dependencies/blocked_by" \
       -F "issue_id=${blocker_id}" >/dev/null; then
    echo "  added      #$blocked blocked by #$blocker  ($label)"
    added=$((added + 1))
  else
    echo "  FAILED     #$blocked blocked by #$blocker  ($label)" >&2
    failed=$((failed + 1))
  fi
}

# CNT-000b (#82)
edge 82 81 'CNT-000b <- FND-002b'
# FND-009 (#83)
edge 83 81 'FND-009 <- FND-002b'
# LOOP-001 (#40)
edge 40 83 'LOOP-001 <- FND-009'
edge 40 30 'LOOP-001 <- DEC-001'
# LOOP-001b (#41)
edge 41 40 'LOOP-001b <- LOOP-001'
# LOOP-002 (#42)
edge 42 83 'LOOP-002 <- FND-009'
# LOOP-003 (#43)
edge 43 83 'LOOP-003 <- FND-009'
# LOOP-004 (#44)
edge 44 43 'LOOP-004 <- LOOP-003'
edge 44 53 'LOOP-004 <- CNT-001'
# LOOP-005 (#45)
edge 45 43 'LOOP-005 <- LOOP-003'
edge 45 53 'LOOP-005 <- CNT-001'
# LOOP-006 (#46)
edge 46 43 'LOOP-006 <- LOOP-003'
edge 46 53 'LOOP-006 <- CNT-001'
# LOOP-007 (#47)
edge 47 43 'LOOP-007 <- LOOP-003'
# LOOP-008 (#48)
edge 48 47 'LOOP-008 <- LOOP-007'
# LOOP-009 (#49)
edge 49 48 'LOOP-009 <- LOOP-008'
# LOOP-010 (#50)
edge 50 45 'LOOP-010 <- LOOP-005'
# LOOP-011 (#51)
edge 51 44 'LOOP-011 <- LOOP-004'
# LOOP-012 (#52)
edge 52 50 'LOOP-012 <- LOOP-010'
edge 52 51 'LOOP-012 <- LOOP-011'
# CNT-001 (#53)
edge 53 81 'CNT-001 <- FND-002b'
edge 53 82 'CNT-001 <- CNT-000b'
# LOOP-013 (#54)
edge 54 53 'LOOP-013 <- CNT-001'
edge 54 43 'LOOP-013 <- LOOP-003'
# CNT-002 (#55)
edge 55 53 'CNT-002 <- CNT-001'
edge 55 32 'CNT-002 <- DEC-003'
edge 55 39 'CNT-002 <- DEC-010'
# LOOP-014 (#56)
edge 56 83 'LOOP-014 <- FND-009'
# LOOP-015 (#57)
edge 57 40 'LOOP-015 <- LOOP-001'
edge 57 42 'LOOP-015 <- LOOP-002'
edge 57 44 'LOOP-015 <- LOOP-004'
edge 57 45 'LOOP-015 <- LOOP-005'
edge 57 46 'LOOP-015 <- LOOP-006'
edge 57 47 'LOOP-015 <- LOOP-007'
edge 57 48 'LOOP-015 <- LOOP-008'
edge 57 49 'LOOP-015 <- LOOP-009'
edge 57 50 'LOOP-015 <- LOOP-010'
edge 57 51 'LOOP-015 <- LOOP-011'
edge 57 52 'LOOP-015 <- LOOP-012'
edge 57 54 'LOOP-015 <- LOOP-013'
edge 57 56 'LOOP-015 <- LOOP-014'
edge 57 55 'LOOP-015 <- CNT-002'
edge 57 31 'LOOP-015 <- DEC-002'
# LOOP-016 (#58)
edge 58 40 'LOOP-016 <- LOOP-001'
edge 58 41 'LOOP-016 <- LOOP-001b'
edge 58 42 'LOOP-016 <- LOOP-002'
edge 58 43 'LOOP-016 <- LOOP-003'
edge 58 44 'LOOP-016 <- LOOP-004'
edge 58 45 'LOOP-016 <- LOOP-005'
edge 58 46 'LOOP-016 <- LOOP-006'
edge 58 47 'LOOP-016 <- LOOP-007'
edge 58 48 'LOOP-016 <- LOOP-008'
edge 58 49 'LOOP-016 <- LOOP-009'
edge 58 50 'LOOP-016 <- LOOP-010'
edge 58 51 'LOOP-016 <- LOOP-011'
edge 58 52 'LOOP-016 <- LOOP-012'
edge 58 54 'LOOP-016 <- LOOP-013'
edge 58 56 'LOOP-016 <- LOOP-014'
edge 58 57 'LOOP-016 <- LOOP-015'
edge 58 55 'LOOP-016 <- CNT-002'
# ARR-001 (#59)
edge 59 58 'ARR-001 <- LOOP-016'
# ARR-002 (#60)
edge 60 59 'ARR-002 <- ARR-001'
# ARR-003 (#61)
edge 61 60 'ARR-003 <- ARR-002'
# ARR-004 (#62)
edge 62 61 'ARR-004 <- ARR-003'
edge 62 49 'ARR-004 <- LOOP-009'
# ARR-005 (#63)
edge 63 59 'ARR-005 <- ARR-001'
edge 63 60 'ARR-005 <- ARR-002'
edge 63 61 'ARR-005 <- ARR-003'
edge 63 62 'ARR-005 <- ARR-004'
# EXP-001 (#64)
edge 64 62 'EXP-001 <- ARR-004'
edge 64 49 'EXP-001 <- LOOP-009'
# EXP-002 (#65)
edge 65 64 'EXP-002 <- EXP-001'
edge 65 33 'EXP-002 <- DEC-004'
# EXP-003 (#66)
edge 66 64 'EXP-003 <- EXP-001'
edge 66 33 'EXP-003 <- DEC-004'
# REL-001 (#67)
edge 67 63 'REL-001 <- ARR-005'
edge 67 65 'REL-001 <- EXP-002'
edge 67 66 'REL-001 <- EXP-003'
# OPS-001 (#68)
edge 68 67 'OPS-001 <- REL-001'
# AI-001 (#69)
edge 69 67 'AI-001 <- REL-001'
edge 69 34 'AI-001 <- DEC-005'
# AI-002 (#70)
edge 70 67 'AI-002 <- REL-001'
# AI-003 (#71)
edge 71 69 'AI-003 <- AI-001'
edge 71 70 'AI-003 <- AI-002'
# AI-004 (#72)
edge 72 71 'AI-004 <- AI-003'
# AI-005 (#73)
edge 73 72 'AI-005 <- AI-004'
# REL-002 (#74)
edge 74 73 'REL-002 <- AI-005'
# HARD-001 (#75)
edge 75 74 'HARD-001 <- REL-002'
# HARD-002 (#76)
edge 76 74 'HARD-002 <- REL-002'
# HARD-003 (#77)
edge 77 74 'HARD-003 <- REL-002'
edge 77 30 'HARD-003 <- DEC-001'
edge 77 34 'HARD-003 <- DEC-005'
edge 77 38 'HARD-003 <- DEC-009'
# HARD-004 (#78)
edge 78 57 'HARD-004 <- LOOP-015'
edge 78 67 'HARD-004 <- REL-001'
# HARD-005 (#79)
edge 79 75 'HARD-005 <- HARD-001'
edge 79 76 'HARD-005 <- HARD-002'
edge 79 77 'HARD-005 <- HARD-003'
edge 79 78 'HARD-005 <- HARD-004'
edge 79 35 'HARD-005 <- DEC-006'
# REL-003 (#80)
edge 80 79 'REL-003 <- HARD-005'

if [ "$APPLY" = "0" ]; then
  echo ""
  echo "dry run: $added to add, $present already present, $failed skipped"
  echo "Re-run with --apply to create them."
else
  echo ""
  echo "done: $added added, $present already present, $failed failed"
fi
[ "$failed" -eq 0 ]
