#!/usr/bin/env node
// Query the Freesound API for CC0 sounds that fill named gaps, and write them as
// a committed candidate-source input.
//
//   FREESOUND_API_KEY=… bun run library:freesound            # query and write
//   FREESOUND_API_KEY=… bun run library:freesound -- --dry   # query, print, no write
//
// This is the fix for the noisy candidate list. The old Freesound candidates came
// from a mined dataset with no per-sound licence, so they were all `unconfirmed`
// and a curator had to open ~1000 pages hunting for CC0 needles. This asks the
// API directly, filters to `license:"Creative Commons 0"` server-side (see
// acquire/freesoundApi.mjs), and writes only CC0 sounds — each already resolved,
// so `library:candidates` can emit them as `verified-cc0` and the curator reviews
// musical quality and provenance, not the licence.
//
// It is NOT a crawler and NOT a "download this tag" mode. It runs the specific,
// named-gap queries in acquire/freesoundGaps.mjs — a person wrote each one — and
// writes only candidate *pages*. Nothing is downloaded for redistribution here;
// the pin → review → commit → ingest path (section 15.5) is unchanged, and a
// Freesound download still needs OAuth at `--pin` time exactly as before.
//
// Output: scripts/starter-library/acquire/candidate-sources/freesound-cc0.json,
// a committed input to `library:candidates` — the same shape as the FSLD input,
// but every entry's licence is already Creative Commons 0. Regenerating it is a
// rare, by-hand step; re-run `library:candidates` afterwards to fold it into
// candidates.json.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { FREESOUND_CC0, searchGap } from "./acquire/freesoundApi.mjs";
import { GAPS } from "./acquire/freesoundGaps.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(
	HERE,
	"acquire",
	"candidate-sources",
	"freesound-cc0.json",
);

/** How many CC0 results to keep per gap. A curator only needs a few per role. */
const PER_GAP = 8;

/**
 * Turn one CC0 API sound into a candidate-source record. The shape mirrors the
 * FSLD input so `generateCandidates.mjs` can treat it the same way — the only
 * difference is `licenseConfidence: "verified-cc0"`, because the API resolved
 * the licence. It is still only a hint (section 4.2): the authoritative position
 * remains the evidence captured at ingest, and the curator still confirms the
 * sound is what it claims and that the uploader made it (section 3.3).
 */
export function soundToRecord(sound, gap) {
	const bpm = sound.bpm ? ` ${Math.round(sound.bpm)} BPM` : "";
	return {
		id: `freesound-gap-${gap.id}-${sound.id}`,
		sourceId: "freesound",
		pageUrl: `https://freesound.org/s/${sound.id}/`,
		note: `${gap.note ?? gap.query}${bpm} — CC0 confirmed via API; audition and confirm provenance`,
		licenseConfidence: "verified-cc0",
		asset: {
			family: gap.family,
			role: gap.role,
			name: sound.name || `Freesound ${sound.id}`,
			genres: gap.genres,
			characters: gap.characters,
			intensity: gap.intensity ?? "medium",
			sourceType: "recorded",
		},
	};
}

/**
 * Run every gap query and collect CC0 records, de-duplicated by Freesound sound
 * ID (the same sound can match two gaps; keep the first, whose gap seeds it best
 * by query order). `fetchImpl` and `token` are injectable for tests.
 */
export async function collectCandidates({
	gaps = GAPS,
	token,
	fetchImpl,
	perGap = PER_GAP,
	log = () => {},
} = {}) {
	const records = [];
	const seenSoundIds = new Set();
	const failures = [];

	for (const gap of gaps) {
		const { ok, sounds, error } = await searchGap(gap, {
			token,
			fetchImpl,
			pageSize: perGap * 2,
		});
		if (!ok) {
			failures.push({ gap: gap.id, error });
			log(`  ${gap.id.padEnd(20)} FAILED: ${error}`);
			continue;
		}
		let kept = 0;
		for (const sound of sounds) {
			if (kept >= perGap) break;
			if (seenSoundIds.has(sound.id)) continue;
			seenSoundIds.add(sound.id);
			records.push(soundToRecord(sound, gap));
			kept++;
		}
		log(`  ${gap.id.padEnd(20)} ${kept} CC0 sounds`);
	}
	return { records, failures };
}

export function buildOutput(records) {
	return {
		version: 1,
		_comment:
			'GENERATED by `library:freesound` from the Freesound API. Every entry is a Creative Commons 0 sound resolved by the API (filter=license:"Creative Commons 0"), so `library:candidates` emits them as verified-cc0. This is NOT a pin list: each is a candidate PAGE a curator auditions for quality and provenance (section 3.3) before anything is pinned. Regenerate with `library:freesound`, then `library:candidates`.',
		license: FREESOUND_CC0,
		gaps: [
			...new Set(records.map((r) => r.id.split("-").slice(2, -1).join("-"))),
		],
		candidates: records,
	};
}

export async function run({
	dry = false,
	token = process.env.FREESOUND_API_KEY,
	fetchImpl,
	log = console.log,
	outPath = OUT_PATH,
} = {}) {
	if (!token) {
		log(
			"No FREESOUND_API_KEY set. Basic search may work but is heavily rate-limited;",
		);
		log(
			"get a free token at https://freesound.org/apiv2/apply/ and export FREESOUND_API_KEY.",
		);
		log("");
	}
	log(`Querying Freesound for CC0 sounds across ${GAPS.length} named gaps:`);
	const { records, failures } = await collectCandidates({
		token,
		fetchImpl,
		log,
	});

	log("");
	log(`Collected ${records.length} CC0 candidates.`);
	if (failures.length > 0) {
		log(`${failures.length} gap queries failed:`);
		for (const f of failures) log(`  - ${f.gap}: ${f.error}`);
	}

	if (dry) {
		log("");
		log("--dry: not writing. Sample of what would be written:");
		for (const r of records.slice(0, 10)) {
			log(
				`  ${r.id.padEnd(40)} ${r.asset.family}/${r.asset.role}  ${r.asset.name}`,
			);
		}
		return { records, failures, written: false };
	}

	if (records.length === 0) {
		log("");
		log("No CC0 candidates collected; leaving the existing file untouched.");
		return { records, failures, written: false };
	}

	writeFileSync(
		outPath,
		`${JSON.stringify(buildOutput(records), null, "\t")}\n`,
	);
	log("");
	log(`Wrote ${records.length} CC0 candidates to ${outPath}`);
	log("Run `bun run library:candidates` to fold them into candidates.json,");
	log("then `bun run library:manage` to audition and pin them.");
	return { records, failures, written: true };
}

if (import.meta.url === `file://${process.argv[1]}`) {
	const dry = process.argv.slice(2).includes("--dry");
	run({ dry }).catch((error) => {
		console.error(error instanceof Error ? error.message : error);
		process.exit(1);
	});
}
